const GET_REQUEST = "GET_REQUEST";
const GET_SUCCESS = "GET_SUCCESS";
const GET_FAILURE = "GET_FAILURE";
const SINGLE_DATA = "SINGLE_DATA";
const DELETE = "DELETE";
export { GET_FAILURE, GET_REQUEST, GET_SUCCESS, SINGLE_DATA, DELETE };
